### ISSUE TITLE
Can't start new game with weekly build on Mac OS X

### ISSUE THREAD

**Issue by jsena210** [freeorion/freeorion#2482]
### Environment

* **FreeOrion Version**: 0.4.8+ 2019-06-11
* **Operating System**: Mac OS X 10.12.6
* **Graphic card used**: NVIDIA GeForce GT 750M
* **Fetched as** 
  * Weekly development build 2019-06-11

### Description
When creating a new game (not "continue" or "quick start"), when you start game, game crashes without GUI error.

If launched via command line, this is what you see when you hit "OK":

main() caught exception(std::exception): boost::bad_any_cast: failed conversion using boost::any_cast
GUIController failed to setup or run the GUI.

### Expected Result
Game starts

### Steps to reproduce
Open app
Hit Single Player
Hit OK

**Comment by jsena210** [comment]
FYI, This bug appeared in weekly build 2019-04-22 and was not manifesting in the build before that.

**Comment by geoffthemedio** [comment]
Any change with build [2019-06-16.ecb7a95](http://sourceforge.net/projects/freeorion/files/FreeOrion/Test/FreeOrion_2019-06-16.ecb7a95_MacOSX_10.9.dmg/download) ?

**Comment by jsena210** [comment]
No change with 2019-06-16

**Comment by geoffthemedio** [comment]
Please post freeorion.log from after attempting to open the galaxy setup window / clicking single player using the latest version. There's new / additional logging that might be helpful, particularly the stuff after the last "parse_file" line.

**Comment by jsena210** [comment]
Here is the stuff past the parse_file:

18:23:04.505278 {0x00007fffe03bc3c0} [info] log : Logger.cpp:198 : Added logger named "network"
18:23:04.505354 {0x00007fffe03bc3c0} [info] log : Logger.cpp:331 : Setting "network" logger threshold to "debug".
18:23:04.505370 {0x00007fffe03bc3c0} [debug] log : LoggerWithOptionsDB.cpp:105 : Configure log source "network" from optionsDB using threshold debug
18:23:04.505388 {0x00007fffe03bc3c0} [debug] network : ClientNetworking.cpp:349 : Attempt to connect to server at one of these addresses:
18:23:04.505458 {0x00007fffe03bc3c0} [debug] network : ClientNetworking.cpp:351 :   tcp::resolver::iterator host_name: 127.0.0.1  address: 127.0.0.1  port: 12346
18:23:06.433023 {0x00007fffe03bc3c0} [debug] network : ClientNetworking.cpp:418 : ConnectToServer() : failed to connect to server.
18:23:06.433113 {0x00007fffe03bc3c0} [debug] client : HumanClientApp.cpp:456 : HumanClientApp::StartServer: /Games/FreeOrion.app/Contents/Executables/freeoriond
18:23:06.433176 {0x00007fffe03bc3c0} [debug] client : HumanClientApp.cpp:490 : ai-config not set.
18:23:06.433198 {0x00007fffe03bc3c0} [debug] client : HumanClientApp.cpp:496 : Launching server process with args: 
18:23:06.433213 {0x00007fffe03bc3c0} [debug] client : HumanClientApp.cpp:498 : "/Games/FreeOrion.app/Contents/Executables/freeoriond"
18:23:06.433227 {0x00007fffe03bc3c0} [debug] client : HumanClientApp.cpp:498 : --resource.path
18:23:06.433240 {0x00007fffe03bc3c0} [debug] client : HumanClientApp.cpp:498 : "/Games/FreeOrion.app/Contents/Resources/default"
18:23:06.433253 {0x00007fffe03bc3c0} [debug] client : HumanClientApp.cpp:498 : --singleplayer
18:23:06.433265 {0x00007fffe03bc3c0} [debug] client : HumanClientApp.cpp:498 : --skip-checksum
18:23:06.443096 {0x00007fffe03bc3c0} [debug] client : HumanClientApp.cpp:500 : ... finished launching server process.
18:23:06.443377 {0x00007fffe03bc3c0} [debug] client : HumanClientApp.cpp:530 : Initializing galaxy setup window
18:23:06.443469 {0x00007fffe03bc3c0} [debug] client : GalaxySetupWnd.cpp:963 : GalaxySetupWnd::CompleteConstruction
18:23:06.443496 {0x00007fffe03bc3c0} [debug] client : GalaxySetupWnd.cpp:540 : GalaxySetupPanel::CompleteConstruction
18:23:08.486928 {0x00007fffe03bc3c0} [debug] client : Process.cpp:275 : Process::Impl::Kill calling kill(m_process_id, SIGKILL)
18:23:08.487006 {0x00007fffe03bc3c0} [debug] client : Process.cpp:277 : Process::Impl::Kill calling waitpid(m_process_id, &status, 0)
18:23:08.497547 {0x00007fffe03bc3c0} [debug] client : Process.cpp:279 : Process::Impl::Kill done
18:23:08.497596 {0x00007fffe03bc3c0} [debug] client : HumanClientApp.cpp:387 : HumanClientApp exited cleanly.
18:23:08.530083 {0x00007fffe03bc3c0} [debug] client : Universe.cpp:161 : Reset id allocators with highest object id = -1 and highest design id = -1
18:23:08.530153 {0x00007fffe03bc3c0} [error] client : chmain.cpp:316 : main() caught exception(std::exception): boost::bad_any_cast: failed conversion using boost::any_cast
18:23:08.579804 {0x00007fffe03bc3c0} [debug] client : Sound.cpp:268 : Audio disabled.

**Comment by jsena210** [comment]
Is it possible that something changed in this commit that would have affected it?  As I mentioned the April 22 build is where this started, the build before that (2019-04-15.ce03bef) was okay.

Commits on Apr 17, 2019 
Merge pull request #2421 from o01eg/remove-player-id-playerstatus

**Comment by jsena210** [comment]
also this looks relevant:

Commits on Apr 16, 2019 
Fill AI in lobby from common galaxy setup option.

**Comment by geoffthemedio** [comment]
Can you start the game, go to the options logs tab, set everything to trace, then click the single player button, and then post the resulting log file? It'll be bigger, but hopefully narrow down the cause of the crashing...

AI lobby shouldn't be relevant for a single player game as the lobby is used in a multiplayer game only. Player status is used for AI players, but they don't exist yet when in the galaxy setup screen, so that also shouldn't be relevant.

If you can compile from source, you could try to find the commit that causes the issue. Otherwise I just have to add more log messages to figure out where the issue is. Apparently it's not in OptionsDB::Get, which I edited prior to the current test build.

**Comment by o01eg** [comment]
It looks like game rules issue because universe values' `bad_cast` is handled.

**Comment by geoffthemedio** [comment]
`bad_cast` only appears in stringtable code, so I'm not sure what you're referring to. If you mean `bad_any_cast`, that can occur in a variety of locations, whenever `boost::any` is used. If you're basing this on another log file, please post it.

**Comment by o01eg** [comment]
Yes, I mean `bad_any_case` here could be thrown by `any_cast`:
https://github.com/freeorion/freeorion/blob/e50645b24842e16c24356369499858a00788ce44/universe/ValueRef.cpp#L569
https://github.com/freeorion/freeorion/blob/dc9921beb9c29a1f51fa306ea20739793344ef9f/util/GameRules.h#L88

**Comment by geoffthemedio** [comment]
Do you have reason to think it's coming specifically from `GameRules`? I'll do the same adjustments to that as I did for `OptionsDB` regardless, but specific info would be helpful...

**Comment by o01eg** [comment]
I've search all `any_cast` in the code and all other is option or have `bad_any_case` handled.

**Comment by jsena210** [comment]
[freeorion.log.zip](https://github.com/freeorion/freeorion/files/3305768/freeorion.log.zip)

Here is the log file with everything set to trace.

**Comment by jsena210** [comment]
Last night I tried setting up a multiplayer game + adding AI, and it runs.  So I agree it's probably not ai-related.  Something specific to setting up a Single Player game perhaps.

**Comment by geoffthemedio** [comment]
And while I can try to make things more crash proof, there is probably some related cause of the crash that should be fixed and might cause non-crash issues...

**Comment by geoffthemedio** [comment]
try-catch around the `any_cast` added to `GameRules`: https://github.com/freeorion/freeorion/commit/07c617144f8e5d97e157ad5112fe058a28f337d2

**Comment by Vezzra** [comment]
Got around to narrowing down the commit which introduced the issue (via `git bisect`):

77ed6e896920ca106f56202f10f7e18aa86da618

HTH

**Comment by geoffthemedio** [comment]
hmm... strange... not sure why 77ed6e8 would be an issue.

**Comment by Vezzra** [comment]
> try-catch around the `any_cast` added to `GameRules`: https://github.com/freeorion/freeorion/commit/07c617144f8e5d97e157ad5112fe058a28f337d2

Still crashing on OSX with the latest test builds I just uploaded (8f89118995edb6aada349511d72f1b0d47850230).

> hmm... strange... not sure why 77ed6e8 would be an issue.

I know, but that's what `git bisect` yielded. Hadn't the time to double check it, will try to do so if I manage to find some more time for this.

**Comment by Vezzra** [comment]
Has there been any progress on this? Anyone trying to do anything about it? I haven't been able to get back to verify the results of my bisecting unfortunately.

This is a serious major bug and will block the upcoming 0.4.9 release until it can be solved...

**Comment by geoffthemedio** [comment]
I can't reproduce the issue and don't know what else to try changing.

**Comment by Vezzra** [comment]
Which leaves us with two options:

* Delay 0.4.9 until someone on a Mac gets around to track down and fix this issue. Unfortunately, that could take a *very* long time.

* Have a 0.4.9 release with broken Mac support.

None of these options sound appealing, but I don't see any other solution. As bad as the second option is, the first one seems to be much worse (IMO).

@geoffthemedio? What would be your preferred course of action?

**Comment by o01eg** [comment]
@Vezzra What if try to build with newer SDK with boost 1.70?

**Comment by Vezzra** [comment]
Could give that a try... when I get around to it. That is going to take a while, unfortunately.

**Comment by jsena210** [comment]
Can I do anything to help?  I could reinstall XCode and compile (although it seems somebody is still doing that weekly)... obviously I can test if you want to point me at a branch build.

**Comment by geoffthemedio** [comment]
If you can reproduce the crash issue, and then find out at what commit it starts happenning for you, that would be helpful, along with subsequent testing.

**Comment by jsena210** [comment]
Not sure what specific commit other than the weekly builds.  April 22 build is where the issue started happening, the build before that (2019-04-15.ce03bef) didn't have the issue.

**Comment by Vezzra** [comment]
@jsena210, if you want to help, you could try to verify if my narrowing down the introduction of the issue being in commit 77ed6e896920ca106f56202f10f7e18aa86da618 is correct.

Are you familiar with git? Do you know how to checkout specific commits to build and run them?

If yes, please checkout, build and run the following two commits from the FO repository:

77ed6e896920ca106f56202f10f7e18aa86da618
368f1bc0a64a62f16e8722a1e039af1b8c238e8d

The first one should have the issue (which means, it should crash), the second one should not (which means, it should work). If you can reproduce that on your system, that would confirm that the issue has been introduced in commit 77ed6e896920ca106f56202f10f7e18aa86da618.

**Comment by jsena210** [comment]
Sorry, really not familiar with GitHub.  I have the master branch but I have no idea how to pull 368f1bc .  I'm using GitHub desktop.  I'm going to try to figure it out but if there is an easy way let me know.

**Comment by Vezzra** [comment]
Ok, hm, that's unfortunate. I don't use the GitHub Desktop client, so I can't help you there - AFAIK it should be possible to check out any commit with it.

You can try using other git GUI clients, depending on your platform there are several available. I use [Fork](https://fork.dev/). Others are [SourceTree](https://www.sourcetreeapp.com/) and [GitKraken](https://www.gitkraken.com/). All of those should be free for noncommercial use.

**Comment by geoffthemedio** [comment]
Maybe https://github.com/freeorion/freeorion/commit/e26459d89e217d57620ac1f66e78d9bd96cee530 helps?

**Comment by Vezzra** [comment]
@jsena210, next weeks test builds will include the patch @geoffthemedio referred to above - can you report back if these builds resolved the issue for you?

**Comment by jsena210** [comment]
i look forward to giving it a try!

On Sep 8, 2019, at 8:24 AM, Vezzra <notifications@github.com> wrote:

@jsena210, next weeks test builds will include the patch @geoffthemedio referred to above - can you report back if these builds resolved the issue for you?

**Comment by Vezzra** [comment]
@jsena210, @geoffthemedio, new test builds now available. Did a quick test myself, unfortunately the issue still persists, at least on my system. @jsena210, although I doubt that it will be any different on your system, can you give it a try nonetheless?

**Comment by geoffthemedio** [comment]
Can you post a new trace-level client log from after producing this crash? Also please explicitly restate what steps are taken to produce the crash... I'm unsure of what is involved between the logs and various posts above.

**Comment by jsena210** [comment]
Just tried new build, same (crashed) result.

Steps to reproduce:
(1) Launch FreeOrion
(2) Single Player
(3) OK

I again launched the UI, went into the options and set all the logs to
"trace", then reproduced the issue as stated above... see trace attached.

**Comment by geoffthemedio** [comment]
>  see trace attached.

I don't see anything attached...

**Comment by geoffthemedio** [comment]
@Vezzra can you try after https://github.com/freeorion/freeorion/commit/a487ccd8d134a8561365816f8904aae1683ca108 and post freeorion.log regardless of the outcome?

**Comment by jsena210** [comment]
[freeorion.log](https://github.com/freeorion/freeorion/files/3603130/freeorion.log)
hopefully this time it is attached.

**Comment by jsena210** [comment]
FIXED!  Build c7b5a6a is working for single player.

**Comment by geoffthemedio** [comment]
I still need logs...

And if you investigate further, probably one of the galaxy setup settings isn't being transferred properly to the server.

**Comment by Vezzra** [comment]
I can confirm that the last test builds fixed at least the crash (haven't had the time to check if all galaxy setup settings have been properly transferred to the server).

@geoffthemedio:

> I still need logs...

Of the most recent commit, the last test builds, commit a487ccd8d134a8561365816f8904aae1683ca108...?

**Comment by geoffthemedio** [comment]
latest commit as available

**Comment by Vezzra** [comment]
Log for a test run of the last weekly test builds (26814993f1befca8596898e621569146ad136ed4), trace enabled for everything (to be sure):

[freeorion.log.zip](https://github.com/freeorion/freeorion/files/3680774/freeorion.log.zip)

The unzipped log file is very large (~37MB), but I guess that's to be expected with trace logging on...

**Comment by geoffthemedio** [comment]
In the log there are a series of lines similar to
`OptionsDB::Option::SetFromValue expected type 17GalaxySetupOption but got value of type 17GalaxySetupOption`

For some reason on OSX, the typeids aren't considered to be matching, even though their names are the same.... But the subsequent actual setting of the value of the option still appears to work, so maybe it's just an constness issue...?

Regardless, if setting setup options works, then apparently it's fine as is...

@Vezzra could you check with https://github.com/freeorion/freeorion/commit/94046b8bc2e9a5f070f53745a1e2efecb5cd0048 applied, by starting the program and starting a new single player game via the single player setup dialog? Don't need trace logging, just look for whether those lines like the above are still present.

**Comment by geoffthemedio** [comment]
I'm going to call this resolved. If there is an issue with galaxy setup options not working, then that can be a separate issue.

**Comment by Vezzra** [comment]
@geoffthemedio, when trying to build 94046b8bc2e9a5f070f53745a1e2efecb5cd0048, I'm getting *a lot* of these:

```
/Users/user/SoftwareProjekte/FO/main/src/parse/../util/OptionsDB.h:450:41: error: expected a qualified name after 'typename'
    if (value.type() != typeid(typename const T))
```

**Comment by geoffthemedio** [comment]
Ugh. Maybe without the `typename` then...?

Re-pushed to test... https://github.com/freeorion/freeorion/commit/a425a3098373f0ca805c50a8b9a2da6760967a7c

Edit: TravisCI build appears OK on OSX, but a look at the logs would still be helpful.

**Comment by Vezzra** [comment]
Builds ok now, but the errors still happen:
```
12:12:38.824229 {0x0000000108d845c0} [error] client : OptionsDB.h:451 : OptionsDB::Option::SetFromValue expected type 5Shape but got value of type 5Shape
12:12:38.824328 {0x0000000108d845c0} [error] client : OptionsDB.h:451 : OptionsDB::Option::SetFromValue expected type 17GalaxySetupOption but got value of type 17GalaxySetupOption
12:12:38.824366 {0x0000000108d845c0} [error] client : OptionsDB.h:451 : OptionsDB::Option::SetFromValue expected type 17GalaxySetupOption but got value of type 17GalaxySetupOption
12:12:38.824388 {0x0000000108d845c0} [error] client : OptionsDB.h:451 : OptionsDB::Option::SetFromValue expected type 17GalaxySetupOption but got value of type 17GalaxySetupOption
12:12:38.824409 {0x0000000108d845c0} [error] client : OptionsDB.h:451 : OptionsDB::Option::SetFromValue expected type 17GalaxySetupOption but got value of type 17GalaxySetupOption
12:12:38.824429 {0x0000000108d845c0} [error] client : OptionsDB.h:451 : OptionsDB::Option::SetFromValue expected type 17GalaxySetupOption but got value of type 17GalaxySetupOption
12:12:38.824449 {0x0000000108d845c0} [error] client : OptionsDB.h:451 : OptionsDB::Option::SetFromValue expected type 17GalaxySetupOption but got value of type 17GalaxySetupOption
12:12:38.824475 {0x0000000108d845c0} [error] client : OptionsDB.h:451 : OptionsDB::Option::SetFromValue expected type 10Aggression but got value of type 10Aggression
```

**Comment by geoffthemedio** [comment]
I dunno then... perhaps there's a better way to check the types, but I'm not sure what it is, and the current error messages presumably aren't causing problems besides a bit of log spam...

**Comment by Vezzra** [comment]
Well, what I can tell from running a couple of quick tests, the options you select in the single player setup dialog are all applied correctly, so yes, aside from those weird error messages nothing seems to be wrong.

Guess we can leave it as is for now.
