### ISSUE TITLE
Forums Not Working

### ISSUE THREAD

**Issue by geoffthemedio** [freeorion/freeorion#2605]
Attempting to access the forums at https://www.freeorion.org/forum/ gives an error page:
````
General Error
SQL ERROR [ mysqli ]

Access denied for user 'dbname_8'@'209.68.1.110' (using password: YES) [1045]

An sql error occurred while fetching this page. Please contact an administrator if this problem persists.
````

**Comment by geoffthemedio** [comment]
The Wiki at https://www.freeorion.org/index.php/Main_Page still seems to work

**Comment by geoffthemedio** [comment]
When connected with SSH, the results are similar. MySQL dumps work fine for the wiki, but don't work for the forums.

**Comment by geoffthemedio** [comment]
The problem might be bandwidth usage, which is currently at 268% of the limit (presumably monthly?). Daily usage stats are about 4-5X what they were 2 months ago. This is probably related to the large numbers of unregistered accounts that have been accessing the forums recently.

**Comment by Oberlus** [comment]
Anything we can do?

**Comment by adrian5** [comment]
Be sure to check the origin of the visitors. If they originate from a narrow IP range in a non-western country (e.g. China), then blocking that would be a quick band-aid.

**Comment by geoffthemedio** [comment]
If I could access the forums, I would try that. From the limited investigation of the unregistered accounts I did a week or two ago, they did appear to originate in China.

**Comment by swaqvalley** [comment]
Another forum I frequent was also bombarded by China-originated DDoS recently. I think they had to block a range of IP addresses at the firewall and implement some anti-DDoS solutions.

**Comment by geoffthemedio** [comment]
I've gotten some updates from the host. Reportedly 

> the database ... was disabled yesterday due to its current size and a large number of Chinese IP addresses flooding freeorion.org.  Attempting to block each IP address was not reducing the load amount for the server, ergo the database itself was disabled to prevent further disruption or other potential issues.

Reportedly we have now set the site up to use CloudFlare, and I've asked the host security / support if there's anything else we can do to mitigate the issue.

**Comment by geoffthemedio** [comment]
The forums are back online at the moment, though again are being heavily visited by guests.

**Comment by geoffthemedio** [comment]
The host informs me that the CloudFlare cache is in place and is mitigating the traffic. I've also added a range of (reporetedly?) Chinese IPs that were the majority of guess users accessing the forums to the PHPBB block list, which immediately dropped the concurrent users from 300 to 50, the latter being mostly CloudFlare IPs.

**Comment by geoffthemedio** [comment]
That looks to be related to how many users are trying to connect, not how much bandwidth has been or is being used.

**Comment by Oberlus** [comment]
All right. So FreeOrion.org/forum is being bombed constantly. I've seen that message many times in the last few weeks.

PS: It's being a pain in the ass. I've tried to log in the forum a few times last hour, no way.

**Comment by swaqvalley** [comment]
I am still getting the max_user_connections message as well maybe 20% of the time. When the main page does load it says there are ~50 users online so it seems that the DDoS connections are still saturating the server even if they are being blocked from actually accessing the site.

**Comment by adrian5** [comment]
Strange though that the users hitting the forum were only a few hundred (if that's accurate). Does the server run stuff other than the Wiki & Forum? Assuming this is not a deliberate DDoS, but rather an extensive crawling attempt, even a small server should be able to handle this with its software firewall alone.

Edit: Wiki and Forums seem smooth here at the moment.

**Comment by geoffthemedio** [comment]
It's a shared server, so other sites hosted by Pair will be on the same machine. They won't block ranges of IPs on the server level as that could affect legit traffic to other sites.

**Comment by Vezzra** [comment]
As this is a purely infrastructure issue, I don't see any point assigning this to a milestone...

**Comment by geoffthemedio** [comment]
I didn't want to release without functional forums....

**Comment by o01eg** [comment]
Is it possible to restrict guest users only so they cannot use more than N database connections?

**Comment by geoffthemedio** [comment]
If you can find a PHPBB setting I can try it...

**Comment by Vezzra** [comment]
@geoffthemedio,

> I didn't want to release without functional forums....

Considering how much that impedes communications and coordination of development efforts, I don't expect us to manage to get the release out while the forum has these issues anyway. But I can see your point.

**Comment by o01eg** [comment]
> If you can find a PHPBB setting I can try it...

I expected there to be a connection pool where it possible to enforce limits, but it looks like it wasn't the case.

**Comment by Oberlus** [comment]
Signing in the forum is broken. Introducing user name and password does nothing. Maybe it's related to all this DDoS burden, or maybe it's something new.

Edit: actually, it sometimes works, but I won't stay logged in for more than a few seconds, so get no time to post (when you click "submit" it presents you with the login page again).

Edit2: It's solved now. I can stay logged as normal.

**Comment by geoffthemedio** [comment]
@Oberlus I've not seen or heard reports of anything similar.

**Comment by Oberlus** [comment]
@geoffthemedio I have never encountered it before.
Found this by searching for "phpbb login not working":
https://www.phpbb.com/community/viewtopic.php?p=14850301
That one was a problem with cookies (so client-side). I have done nothing on my side to break or fix anything, so I don't know. I'll happilly forget about this unless it happens again.

**Comment by Oberlus** [comment]
I bet this issue can be closed.

**Comment by Vezzra** [comment]
Anyone still encountering any issues with the forums? Otherwise this can be closed...

**Comment by geoffthemedio** [comment]
Daily website host bandwidth usage has dropped dramatically after the CAPTCHA for Hong Kong IPs at the CDN was enabled.

![BW_Usage](https://user-images.githubusercontent.com/11386908/68034016-39325b80-fcc1-11e9-82bf-bda046e82bce.png)

I didn't want to close anything before checking what effect that had, as the bandwidth usage last month was about 380% of the allowance by the hosting plan, with substantial overage charges.

But now that it seems to have stabilized at a reasonable rate, I think this can be closed.
