### ISSUE TITLE
error: ‘_1’ was not declared in this scope

### ISSUE THREAD

**Issue by l29ah** [freeorion/freeorion#2936]
Bug Report
==========

Environment
-----------

* **FreeOrion Version**: b7a2164a8d7b6889e96488ed1ebdb065fa1647a0
* **Operating System**: Gentoo GNU/Linux

Description
-----------

```
‰ make                                                                             
[  0%] Building CXX object GG/CMakeFiles/GiGi.dir/src/dialogs/ColorDlg.cpp.o
/home/l29ah/projects/freeorion/GG/src/dialogs/ColorDlg.cpp: In member function ‘virtual void GG::ColorDlg::CompleteConstruction()’:
/home/l29ah/projects/freeorion/GG/src/dialogs/ColorDlg.cpp:622:56: error: ‘_1’ was not declared in this scope
  622 |         boost::bind(&ColorDlg::RedSliderChanged, this, _1, _2, _3));
      |                                                        ^~
/home/l29ah/projects/freeorion/GG/src/dialogs/ColorDlg.cpp:622:56: note: suggested alternatives:
In file included from /usr/include/boost/mpl/aux_/include_preprocessed.hpp:37,
                 from /usr/include/boost/mpl/placeholders.hpp:43,
                 from /usr/include/boost/iterator/iterator_categories.hpp:16,
                 from /usr/include/boost/iterator/iterator_facade.hpp:13,
                 from /usr/include/boost/range/iterator_range_core.hpp:27,
                 from /usr/include/boost/range/iterator_range.hpp:13,
                 from /usr/include/boost/range/as_literal.hpp:22,
                 from /usr/include/boost/algorithm/string/trim.hpp:19,
                 from /home/l29ah/projects/freeorion/GG/GG/Enum.h:40,
                 from /home/l29ah/projects/freeorion/GG/GG/Base.h:38,
                 from /home/l29ah/projects/freeorion/GG/GG/Wnd.h:32,
                 from /home/l29ah/projects/freeorion/GG/GG/Control.h:32,
                 from /home/l29ah/projects/freeorion/GG/GG/TextControl.h:33,
                 from /home/l29ah/projects/freeorion/GG/GG/Button.h:35,
                 from /home/l29ah/projects/freeorion/GG/GG/dialogs/ColorDlg.h:32,
                 from /home/l29ah/projects/freeorion/GG/src/dialogs/ColorDlg.cpp:25:
/usr/include/boost/mpl/aux_/preprocessed/gcc/placeholders.hpp:29:16: note:   ‘mpl_::_1’
   29 | typedef arg<1> _1;
      |                ^~
In file included from /usr/include/boost/algorithm/string/detail/classification.hpp:16,
                 from /usr/include/boost/algorithm/string/classification.hpp:18,
                 from /usr/include/boost/algorithm/string/trim.hpp:23,
                 from /home/l29ah/projects/freeorion/GG/GG/Enum.h:40,
                 from /home/l29ah/projects/freeorion/GG/GG/Base.h:38,
                 from /home/l29ah/projects/freeorion/GG/GG/Wnd.h:32,
                 from /home/l29ah/projects/freeorion/GG/GG/Control.h:32,
                 from /home/l29ah/projects/freeorion/GG/GG/TextControl.h:33,
                 from /home/l29ah/projects/freeorion/GG/GG/Button.h:35,
                 from /home/l29ah/projects/freeorion/GG/GG/dialogs/ColorDlg.h:32,
                 from /home/l29ah/projects/freeorion/GG/src/dialogs/ColorDlg.cpp:25:
/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/functional:211:34: note:   ‘std::placeholders::_1’
  211 |     extern const _Placeholder<1> _1;
      |                                  ^~
In file included from /usr/include/boost/mpl/aux_/include_preprocessed.hpp:37,
                 from /usr/include/boost/mpl/placeholders.hpp:43,
                 from /usr/include/boost/iterator/iterator_categories.hpp:16,
                 from /usr/include/boost/iterator/iterator_facade.hpp:13,
                 from /usr/include/boost/range/iterator_range_core.hpp:27,
                 from /usr/include/boost/range/iterator_range.hpp:13,
                 from /usr/include/boost/range/as_literal.hpp:22,
                 from /usr/include/boost/algorithm/string/trim.hpp:19,
                 from /home/l29ah/projects/freeorion/GG/GG/Enum.h:40,
                 from /home/l29ah/projects/freeorion/GG/GG/Base.h:38,
                 from /home/l29ah/projects/freeorion/GG/GG/Wnd.h:32,
                 from /home/l29ah/projects/freeorion/GG/GG/Control.h:32,
                 from /home/l29ah/projects/freeorion/GG/GG/TextControl.h:33,
                 from /home/l29ah/projects/freeorion/GG/GG/Button.h:35,
                 from /home/l29ah/projects/freeorion/GG/GG/dialogs/ColorDlg.h:32,
                 from /home/l29ah/projects/freeorion/GG/src/dialogs/ColorDlg.cpp:25:
/usr/include/boost/mpl/aux_/preprocessed/gcc/placeholders.hpp:29:16: note:   ‘mpl_::_1’
   29 | typedef arg<1> _1;
      |                ^~
In file included from /usr/include/boost/bind/bind.hpp:2356,
                 from /usr/include/boost/signals2/slot.hpp:15,
                 from /usr/include/boost/signals2/connection.hpp:24,
                 from /usr/include/boost/signals2/signal.hpp:22,
                 from /home/l29ah/projects/freeorion/GG/GG/Button.h:38,
                 from /home/l29ah/projects/freeorion/GG/GG/dialogs/ColorDlg.h:32,
                 from /home/l29ah/projects/freeorion/GG/src/dialogs/ColorDlg.cpp:25:
/usr/include/boost/bind/placeholders.hpp:46:38: note:   ‘boost::placeholders::_1’
   46 | BOOST_STATIC_CONSTEXPR boost::arg<1> _1;
      |                                      ^~
In file included from /usr/include/boost/mpl/aux_/include_preprocessed.hpp:37,
                 from /usr/include/boost/mpl/placeholders.hpp:43,
                 from /usr/include/boost/iterator/iterator_categories.hpp:16,
                 from /usr/include/boost/iterator/iterator_facade.hpp:13,
                 from /usr/include/boost/range/iterator_range_core.hpp:27,
                 from /usr/include/boost/range/iterator_range.hpp:13,
                 from /usr/include/boost/range/as_literal.hpp:22,
                 from /usr/include/boost/algorithm/string/trim.hpp:19,
                 from /home/l29ah/projects/freeorion/GG/GG/Enum.h:40,
                 from /home/l29ah/projects/freeorion/GG/GG/Base.h:38,
                 from /home/l29ah/projects/freeorion/GG/GG/Wnd.h:32,
                 from /home/l29ah/projects/freeorion/GG/GG/Control.h:32,
                 from /home/l29ah/projects/freeorion/GG/GG/TextControl.h:33,
                 from /home/l29ah/projects/freeorion/GG/GG/Button.h:35,
                 from /home/l29ah/projects/freeorion/GG/GG/dialogs/ColorDlg.h:32,
                 from /home/l29ah/projects/freeorion/GG/src/dialogs/ColorDlg.cpp:25:
/usr/include/boost/mpl/aux_/preprocessed/gcc/placeholders.hpp:29:16: note:   ‘mpl_::_1’
   29 | typedef arg<1> _1;
      |                ^~
/home/l29ah/projects/freeorion/GG/src/dialogs/ColorDlg.cpp:622:60: error: ‘_2’ was not declared in this scope
  622 |         boost::bind(&ColorDlg::RedSliderChanged, this, _1, _2, _3));
      |                                                            ^~
/home/l29ah/projects/freeorion/GG/src/dialogs/ColorDlg.cpp:622:60: note: suggested alternatives:
In file included from /usr/include/boost/mpl/aux_/include_preprocessed.hpp:37,
                 from /usr/include/boost/mpl/placeholders.hpp:43,
                 from /usr/include/boost/iterator/iterator_categories.hpp:16,
                 from /usr/include/boost/iterator/iterator_facade.hpp:13,
                 from /usr/include/boost/range/iterator_range_core.hpp:27,
                 from /usr/include/boost/range/iterator_range.hpp:13,
                 from /usr/include/boost/range/as_literal.hpp:22,
                 from /usr/include/boost/algorithm/string/trim.hpp:19,
                 from /home/l29ah/projects/freeorion/GG/GG/Enum.h:40,
                 from /home/l29ah/projects/freeorion/GG/GG/Base.h:38,
                 from /home/l29ah/projects/freeorion/GG/GG/Wnd.h:32,
                 from /home/l29ah/projects/freeorion/GG/GG/Control.h:32,
                 from /home/l29ah/projects/freeorion/GG/GG/TextControl.h:33,
                 from /home/l29ah/projects/freeorion/GG/GG/Button.h:35,
                 from /home/l29ah/projects/freeorion/GG/GG/dialogs/ColorDlg.h:32,
                 from /home/l29ah/projects/freeorion/GG/src/dialogs/ColorDlg.cpp:25:
/usr/include/boost/mpl/aux_/preprocessed/gcc/placeholders.hpp:42:16: note:   ‘mpl_::_2’
   42 | typedef arg<2> _2;
      |                ^~
In file included from /usr/include/boost/algorithm/string/detail/classification.hpp:16,
                 from /usr/include/boost/algorithm/string/classification.hpp:18,
                 from /usr/include/boost/algorithm/string/trim.hpp:23,
                 from /home/l29ah/projects/freeorion/GG/GG/Enum.h:40,
                 from /home/l29ah/projects/freeorion/GG/GG/Base.h:38,
                 from /home/l29ah/projects/freeorion/GG/GG/Wnd.h:32,
                 from /home/l29ah/projects/freeorion/GG/GG/Control.h:32,
                 from /home/l29ah/projects/freeorion/GG/GG/TextControl.h:33,
                 from /home/l29ah/projects/freeorion/GG/GG/Button.h:35,
                 from /home/l29ah/projects/freeorion/GG/GG/dialogs/ColorDlg.h:32,
                 from /home/l29ah/projects/freeorion/GG/src/dialogs/ColorDlg.cpp:25:
/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/functional:212:34: note:   ‘std::placeholders::_2’
  212 |     extern const _Placeholder<2> _2;
      |                                  ^~
In file included from /usr/include/boost/mpl/aux_/include_preprocessed.hpp:37,
                 from /usr/include/boost/mpl/placeholders.hpp:43,
                 from /usr/include/boost/iterator/iterator_categories.hpp:16,
                 from /usr/include/boost/iterator/iterator_facade.hpp:13,
                 from /usr/include/boost/range/iterator_range_core.hpp:27,
                 from /usr/include/boost/range/iterator_range.hpp:13,
                 from /usr/include/boost/range/as_literal.hpp:22,
                 from /usr/include/boost/algorithm/string/trim.hpp:19,
                 from /home/l29ah/projects/freeorion/GG/GG/Enum.h:40,
                 from /home/l29ah/projects/freeorion/GG/GG/Base.h:38,
                 from /home/l29ah/projects/freeorion/GG/GG/Wnd.h:32,
                 from /home/l29ah/projects/freeorion/GG/GG/Control.h:32,
                 from /home/l29ah/projects/freeorion/GG/GG/TextControl.h:33,
                 from /home/l29ah/projects/freeorion/GG/GG/Button.h:35,
                 from /home/l29ah/projects/freeorion/GG/GG/dialogs/ColorDlg.h:32,
                 from /home/l29ah/projects/freeorion/GG/src/dialogs/ColorDlg.cpp:25:
/usr/include/boost/mpl/aux_/preprocessed/gcc/placeholders.hpp:42:16: note:   ‘mpl_::_2’
   42 | typedef arg<2> _2;
      |                ^~
In file included from /usr/include/boost/bind/bind.hpp:2356,
                 from /usr/include/boost/signals2/slot.hpp:15,
                 from /usr/include/boost/signals2/connection.hpp:24,
                 from /usr/include/boost/signals2/signal.hpp:22,
                 from /home/l29ah/projects/freeorion/GG/GG/Button.h:38,
                 from /home/l29ah/projects/freeorion/GG/GG/dialogs/ColorDlg.h:32,
                 from /home/l29ah/projects/freeorion/GG/src/dialogs/ColorDlg.cpp:25:
/usr/include/boost/bind/placeholders.hpp:47:38: note:   ‘boost::placeholders::_2’
   47 | BOOST_STATIC_CONSTEXPR boost::arg<2> _2;
      |                                      ^~
In file included from /usr/include/boost/mpl/aux_/include_preprocessed.hpp:37,
                 from /usr/include/boost/mpl/placeholders.hpp:43,
                 from /usr/include/boost/iterator/iterator_categories.hpp:16,
                 from /usr/include/boost/iterator/iterator_facade.hpp:13,
                 from /usr/include/boost/range/iterator_range_core.hpp:27,
                 from /usr/include/boost/range/iterator_range.hpp:13,
                 from /usr/include/boost/range/as_literal.hpp:22,
                 from /usr/include/boost/algorithm/string/trim.hpp:19,
                 from /home/l29ah/projects/freeorion/GG/GG/Enum.h:40,
                 from /home/l29ah/projects/freeorion/GG/GG/Base.h:38,
                 from /home/l29ah/projects/freeorion/GG/GG/Wnd.h:32,
                 from /home/l29ah/projects/freeorion/GG/GG/Control.h:32,
                 from /home/l29ah/projects/freeorion/GG/GG/TextControl.h:33,
                 from /home/l29ah/projects/freeorion/GG/GG/Button.h:35,
                 from /home/l29ah/projects/freeorion/GG/GG/dialogs/ColorDlg.h:32,
                 from /home/l29ah/projects/freeorion/GG/src/dialogs/ColorDlg.cpp:25:
/usr/include/boost/mpl/aux_/preprocessed/gcc/placeholders.hpp:42:16: note:   ‘mpl_::_2’
   42 | typedef arg<2> _2;
      |                ^~
/home/l29ah/projects/freeorion/GG/src/dialogs/ColorDlg.cpp:622:64: error: ‘_3’ was not declared in this scope
  622 |         boost::bind(&ColorDlg::RedSliderChanged, this, _1, _2, _3));
      |                                                                ^~
/home/l29ah/projects/freeorion/GG/src/dialogs/ColorDlg.cpp:622:64: note: suggested alternatives:
In file included from /usr/include/boost/mpl/aux_/include_preprocessed.hpp:37,
                 from /usr/include/boost/mpl/placeholders.hpp:43,
                 from /usr/include/boost/iterator/iterator_categories.hpp:16,
                 from /usr/include/boost/iterator/iterator_facade.hpp:13,
                 from /usr/include/boost/range/iterator_range_core.hpp:27,
                 from /usr/include/boost/range/iterator_range.hpp:13,
                 from /usr/include/boost/range/as_literal.hpp:22,
                 from /usr/include/boost/algorithm/string/trim.hpp:19,
                 from /home/l29ah/projects/freeorion/GG/GG/Enum.h:40,
                 from /home/l29ah/projects/freeorion/GG/GG/Base.h:38,
                 from /home/l29ah/projects/freeorion/GG/GG/Wnd.h:32,
                 from /home/l29ah/projects/freeorion/GG/GG/Control.h:32,
                 from /home/l29ah/projects/freeorion/GG/GG/TextControl.h:33,
                 from /home/l29ah/projects/freeorion/GG/GG/Button.h:35,
                 from /home/l29ah/projects/freeorion/GG/GG/dialogs/ColorDlg.h:32,
                 from /home/l29ah/projects/freeorion/GG/src/dialogs/ColorDlg.cpp:25:
/usr/include/boost/mpl/aux_/preprocessed/gcc/placeholders.hpp:55:16: note:   ‘mpl_::_3’
   55 | typedef arg<3> _3;
      |                ^~
In file included from /usr/include/boost/algorithm/string/detail/classification.hpp:16,
                 from /usr/include/boost/algorithm/string/classification.hpp:18,
                 from /usr/include/boost/algorithm/string/trim.hpp:23,
                 from /home/l29ah/projects/freeorion/GG/GG/Enum.h:40,
                 from /home/l29ah/projects/freeorion/GG/GG/Base.h:38,
                 from /home/l29ah/projects/freeorion/GG/GG/Wnd.h:32,
                 from /home/l29ah/projects/freeorion/GG/GG/Control.h:32,
                 from /home/l29ah/projects/freeorion/GG/GG/TextControl.h:33,
                 from /home/l29ah/projects/freeorion/GG/GG/Button.h:35,
                 from /home/l29ah/projects/freeorion/GG/GG/dialogs/ColorDlg.h:32,
                 from /home/l29ah/projects/freeorion/GG/src/dialogs/ColorDlg.cpp:25:
/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/functional:213:34: note:   ‘std::placeholders::_3’
  213 |     extern const _Placeholder<3> _3;
      |                                  ^~
In file included from /usr/include/boost/mpl/aux_/include_preprocessed.hpp:37,
                 from /usr/include/boost/mpl/placeholders.hpp:43,
                 from /usr/include/boost/iterator/iterator_categories.hpp:16,
                 from /usr/include/boost/iterator/iterator_facade.hpp:13,
                 from /usr/include/boost/range/iterator_range_core.hpp:27,
                 from /usr/include/boost/range/iterator_range.hpp:13,
                 from /usr/include/boost/range/as_literal.hpp:22,
                 from /usr/include/boost/algorithm/string/trim.hpp:19,
                 from /home/l29ah/projects/freeorion/GG/GG/Enum.h:40,
                 from /home/l29ah/projects/freeorion/GG/GG/Base.h:38,
                 from /home/l29ah/projects/freeorion/GG/GG/Wnd.h:32,
                 from /home/l29ah/projects/freeorion/GG/GG/Control.h:32,
                 from /home/l29ah/projects/freeorion/GG/GG/TextControl.h:33,
                 from /home/l29ah/projects/freeorion/GG/GG/Button.h:35,
                 from /home/l29ah/projects/freeorion/GG/GG/dialogs/ColorDlg.h:32,
                 from /home/l29ah/projects/freeorion/GG/src/dialogs/ColorDlg.cpp:25:
/usr/include/boost/mpl/aux_/preprocessed/gcc/placeholders.hpp:55:16: note:   ‘mpl_::_3’
   55 | typedef arg<3> _3;
      |                ^~
In file included from /usr/include/boost/bind/bind.hpp:2356,
                 from /usr/include/boost/signals2/slot.hpp:15,
                 from /usr/include/boost/signals2/connection.hpp:24,
                 from /usr/include/boost/signals2/signal.hpp:22,
                 from /home/l29ah/projects/freeorion/GG/GG/Button.h:38,
                 from /home/l29ah/projects/freeorion/GG/GG/dialogs/ColorDlg.h:32,
                 from /home/l29ah/projects/freeorion/GG/src/dialogs/ColorDlg.cpp:25:
/usr/include/boost/bind/placeholders.hpp:48:38: note:   ‘boost::placeholders::_3’
   48 | BOOST_STATIC_CONSTEXPR boost::arg<3> _3;
      |                                      ^~
In file included from /usr/include/boost/mpl/aux_/include_preprocessed.hpp:37,
                 from /usr/include/boost/mpl/placeholders.hpp:43,
                 from /usr/include/boost/iterator/iterator_categories.hpp:16,
                 from /usr/include/boost/iterator/iterator_facade.hpp:13,
                 from /usr/include/boost/range/iterator_range_core.hpp:27,
                 from /usr/include/boost/range/iterator_range.hpp:13,
                 from /usr/include/boost/range/as_literal.hpp:22,
                 from /usr/include/boost/algorithm/string/trim.hpp:19,
                 from /home/l29ah/projects/freeorion/GG/GG/Enum.h:40,
                 from /home/l29ah/projects/freeorion/GG/GG/Base.h:38,
                 from /home/l29ah/projects/freeorion/GG/GG/Wnd.h:32,
                 from /home/l29ah/projects/freeorion/GG/GG/Control.h:32,
                 from /home/l29ah/projects/freeorion/GG/GG/TextControl.h:33,
                 from /home/l29ah/projects/freeorion/GG/GG/Button.h:35,
                 from /home/l29ah/projects/freeorion/GG/GG/dialogs/ColorDlg.h:32,
                 from /home/l29ah/projects/freeorion/GG/src/dialogs/ColorDlg.cpp:25:
/usr/include/boost/mpl/aux_/preprocessed/gcc/placeholders.hpp:55:16: note:   ‘mpl_::_3’
   55 | typedef arg<3> _3;
      |                ^~
make[2]: *** [GG/CMakeFiles/GiGi.dir/build.make:83: GG/CMakeFiles/GiGi.dir/src/dialogs/ColorDlg.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:774: GG/CMakeFiles/GiGi.dir/all] Error 2
make: *** [Makefile:172: all] Error 2
```

**Comment by adrianbroher** [comment]
@l29ah Do you have also a known good commit?

**Comment by Oberlus** [comment]
This works for me (Ubuntu 18.04, boost 1.65).
AFAIK, it also worked for @l29ah until he upgraded boost (from what version to what version, idk).

**Comment by l29ah** [comment]
No i don't.
Boost upgraded to 1.73.0.

**Comment by Voker57** [comment]
Not a boost expert, but problem appears to be boost' bindings addressing by _$number, which was long deprecated and by 1.73 finally disabled, which causes the error. There was no good commit in Freeorion. Adding "using namespace boost::placeholders;" or using newer method should fix it.

**Comment by geoffthemedio** [comment]
Ideally the uses of `boost::bind` would be switched to `std::bind`, and `boost::placeholders` to `std::placeholders`, although there are issues with ambiguous definitions of `_1` and similar between boost and std.

**Comment by geoffthemedio** [comment]
@l29ah Could you try with #2937 applied and let me know where it still fails to build? There are lots of uses of the `_1` style placeholders so I likely missed some, amongst other potential problems I can't reproduce on Windows with Boost 1.70

**Comment by geoffthemedio** [comment]
Additional issues remain, but seemingly the issues in this bug report were resolved.
