### ISSUE TITLE
Python argument type - C++ mismatch

### ISSUE THREAD

**Issue by Thinker55** [freeorion/freeorion#3304]
I'm getting this for all AI races at startup:
````
[08 Feb 20:58:34] AI_1: AI_Error: AI script error : FreeOrionAI.py:_error_handler():73  - Exception Python argument types in
    None.None(planet)
did not match C++ signature:
    None(PopCenter {lvalue}) occurred during generateOrders
Traceback (most recent call last):
  File "/home/stephen/Projects/freeorion-project/freeorion/default/python/AI/FreeOrionAI.py", line 70, in _error_handler
    res = func(*args, **kwargs)
  File "/home/stephen/Projects/freeorion-project/build/default/python/common/listeners.py", line 42, in wrapper
    res = funct(*args)
  File "/home/stephen/Projects/freeorion-project/freeorion/default/python/AI/FreeOrionAI.py", line 302, in generateOrders
    debug("CapitalID: " + str(planet_id) + " Name: " + planet.name + " Species: " + planet.speciesName)
Boost.Python.ArgumentError: Python argument types in
    None.None(planet)
did not match C++ signature:
    None(PopCenter {lvalue})
Local context: {'aggression_name': 'Cautious', 'planet': P_2008<Stronghold Dosis I>, 'planet_id': 2008, 'universe': <freeOrionAIInterface.universe object at 0x7fbd592c5710>, 'random_seed': 'PKD7bTCa00001Harmony', 'turn_uid': '29aeca3541', 'aistate': <AIstate.AIstate object at 0x7fbd592ba860>, 'turn': 1, 'empire': E_2<Harmony>, 'rule_value': '0', 'rule_name': 'RULE_UNSEEN_STEALTHY_PLANETS_INVISIBLE', 'rules': <freeOrionAIInterface.GameRules object at 0x7fbd592aed50>}
````
It shows up in the Messages window.  I tried to configure log files, but I don't seem to be getting anything.
Environment is SuSE LEAP 15.2 (Fresh install)
Freeorion build is 0.4.10+ 2021-02-06.a7b140f
Boost is v1.66 (I had to softlink to get boost_python36 to show up)
GCC8
CMake 3.1

**Comment by geoffthemedio** [comment]
Looks like the issue discussed here: https://github.com/freeorion/freeorion/pull/3300#issuecomment-775517536

And reverted here: https://github.com/freeorion/freeorion/commit/18ba137de79f15949ff9f0579c346029502d8643

**Comment by Thinker55** [comment]
Perhaps.  I know that I get a dialog that says there were errors in universe creation, and the initial messages from the AI races do not appear due to the errors.  I thought perhaps that I was using the wrong gcc version, so I set the CMAKE_C_COMPILER and CMAKE_CXX_COMPILER variables.  No change that I could see.  This seems a bit more of an issue than #3300.  Game play is definitely impacted.

**Comment by Thinker55** [comment]
I'm finding this in the MAKE logs:
````
In file included from /home/stephen/Projects/freeorion-project/freeorion/UI/CUISpin.h:8,
                 from /home/stephen/Projects/freeorion-project/freeorion/UI/GalaxySetupWnd.cpp:4:
/home/stephen/Projects/freeorion-project/freeorion/GG/GG/Spin.h: In instantiation of ‘void GG::Spin<T>::ValueUpdated(const string&) [with T = int; std::__cxx11::string = std::__cxx11::basic_string<char>]’:
/home/stephen/Projects/freeorion-project/freeorion/GG/GG/Spin.h:419:51:   required from ‘void GG::Spin<T>::ConnectSignals() [with T = int]’
/home/stephen/Projects/freeorion-project/freeorion/GG/GG/Spin.h:179:5:   required from ‘void GG::Spin<T>::CompleteConstruction() [with T = int]’
/home/stephen/Projects/freeorion-project/freeorion/UI/CUISpin.h:33:42:   required from ‘void CUISpin<T>::CompleteConstruction() [with T = int]’
/home/stephen/Projects/freeorion-project/freeorion/GG/GG/Wnd.h:347:9:   required from ‘static std::shared_ptr<_Tp> GG::Wnd::Create(Args&& ...) [with T = CUISpin<int>; Args = {int&, int, const int&, const int&, bool}]’
/home/stephen/Projects/freeorion-project/freeorion/UI/GalaxySetupWnd.cpp:309:110:   required from here
/home/stephen/Projects/freeorion-project/freeorion/GG/GG/Spin.h:429:7: warning: catching polymorphic type ‘class boost::bad_lexical_cast’ by value [-Wcatch-value=]
     } catch (boost::bad_lexical_cast) {
       ^~~~~
/home/stephen/Projects/freeorion-project/freeorion/GG/GG/Spin.h: In instantiation of ‘void GG::Spin<T>::ValueUpdated(const string&) [with T = double; std::__cxx11::string = std::__cxx11::basic_string<char>]’:
/home/stephen/Projects/freeorion-project/freeorion/GG/GG/Spin.h:419:51:   required from ‘void GG::Spin<T>::ConnectSignals() [with T = double]’
/home/stephen/Projects/freeorion-project/freeorion/GG/GG/Spin.h:179:5:   required from ‘void GG::Spin<T>::CompleteConstruction() [with T = double]’
/home/stephen/Projects/freeorion-project/freeorion/UI/CUISpin.h:33:42:   required from ‘void CUISpin<T>::CompleteConstruction() [with T = double]’
/home/stephen/Projects/freeorion-project/freeorion/GG/GG/Wnd.h:347:9:   required from ‘static std::shared_ptr<_Tp> GG::Wnd::Create(Args&& ...) [with T = CUISpin<double>; Args = {double&, double, const double&, const double&, bool}]’
/home/stephen/Projects/freeorion-project/freeorion/UI/GalaxySetupWnd.cpp:358:115:   required from here
/home/stephen/Projects/freeorion-project/freeorion/GG/GG/Spin.h:429:7: warning: catching polymorphic type ‘class boost::bad_lexical_cast’ by value [-Wcatch-value=]
````
I don't know how serious it is.

**Comment by Thinker55** [comment]
Sorry, the above appears during creation of GalaxySetupWnd.cpp.o -- which would appear to be the broken piece.

**Comment by geoffthemedio** [comment]
Catching an exception by value instead of reference is not a major problem, and that code is not realted to the AIs or server anyway.

The error messages in chat from the AIs are not (directly) related to universe generation, as they happen when the AIs plays their turns after a game starts, and the messages that appear in chat are the same as what was in the linked comment and that were fixed by the linked commit. _edit: though the cause of the universe generation error and AI error actually were the same issue with the Python API /edit_

If you "get a dialog that says there were errors in universe creation" then post that, otherwise we can't diagnose it. But update to the latest master first, as it's probably already fixed anyway.

**Comment by Thinker55** [comment]
Okay, I will update to the latest master and re-compile, then advise as to whether the problem persists.

**Comment by Thinker55** [comment]
Re-compile was successful.  Thanks.
